//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chanchos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int recordId { get; set; }
        public string cartId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
