//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chanchos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChanchosUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChanchosUser()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int userId { get; set; }
        public string name { get; set; }
        public string passwords { get; set; }
        public int age { get; set; }
        public string address { get; set; }
        public string phoneNo { get; set; }
        public string roles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
