//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chanchos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChanchosUser
    {
        public int userId { get; set; }
        public string name { get; set; }
        public string passwords { get; set; }
        public Nullable<int> age { get; set; }
        public string address { get; set; }
        public string phoneNo { get; set; }
        public string roles { get; set; }
    }
}
